spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          keycloak:
            provider: ${KEYCLOAK_PROVIDER}
            authorization-grant-type: ${KEYCLOAK_AUTHORIZATION_GRANT_TYPE}
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope:
              - ${KEYCLOAK_SCOPE}
  flyway:
    locations:
      - classpath:/db/{vendor}/common
      - classpath:/db/{vendor}/prod
    clean-disabled: true
  docker:
    compose:
      enabled: true
keycloak:
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  url: ${KEYCLOAK_URL}
header:
  secret: ${HEADER_SECRET}
garage:
  bucket: ${GARAGE_BUCKET}
  endpoint: ${GARAGE_ENDPOINT}
  key: ${GARAGE_ACCESS_KEY}
  secret: ${GARAGE_SECRET_KEY}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never