CREATE TABLE project_technologies
(
    project_id   BIGINT NOT NULL,
    technologies VARCHAR(255)
);

CREATE TABLE projects
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(36),
    user_id        VARCHAR(255),
    start_date     date,
    end_date       date,
    visibility     BOOLEAN,
    live_url       VARCHAR(255),
    repository_url VARCHAR(255),
    role           VARCHAR(255),
    challenge      VARCHAR(255),
    solution       VARCHAR(255),
    result         VARCHAR(255),
    thumbnail      VARCHAR(255),
    diagram        VARCHAR(255),
    demo           VARCHAR(255),
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                   VARCHAR(255) NOT NULL,
    role                 VARCHAR(255),
    language             VARCHAR(255),
    theme                VARCHAR(255),
    date_format          VARCHAR(255),
    profile_visibility   VARCHAR(255),
    profile_discoverable VARCHAR(255),
    about                VARCHAR(255),
    location             VARCHAR(255),
    website              VARCHAR(255),
    verified             BOOLEAN,
    avatar               VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE project_technologies
    ADD CONSTRAINT fk_project_technologies_on_project FOREIGN KEY (project_id) REFERENCES projects (id);