ALTER TABLE projects ALTER COLUMN challenge TYPE TEXT;
ALTER TABLE projects ALTER COLUMN solution TYPE TEXT;
ALTER TABLE projects ALTER COLUMN result TYPE TEXT;
ALTER TABLE projects ALTER COLUMN thumbnail TYPE TEXT;
ALTER TABLE projects ALTER COLUMN diagram TYPE TEXT;
ALTER TABLE projects ALTER COLUMN demo TYPE TEXT;