name: Deploy

on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout

      - uses: actions/setup-java
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: ./mvnw clean package -Pprod -DskipTests

      - name: Upload JAR
        uses: appleboy/scp-action
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.jar"
          target: "/tmp/"
          strip_components: 1

      - name: Deploy
        uses: appleboy/ssh-action
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER}}
          key: ${{ secrets.SERVER_SSH_KEY}}
          script: |
            mv /tmp/*.jar /tmp/app.jar
            bash /opt/springapp/deploy.sh
